"""
HTML reporter — generate a standalone, self-contained HTML dashboard.
No external dependencies at runtime (all CSS/JS inlined).
"""
from __future__ import annotations

from pathlib import Path

from ragcheck.core.schema import EvalReport

# ---------------------------------------------------------------------------
# Inline template (Jinja2-style but rendered via str.format to avoid
# requiring Jinja2 as a hard dep; uses {{ }} for template vars)
# ---------------------------------------------------------------------------

_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>RAGcheck Report — {dataset_name}</title>
<style>
  :root {{
    --bg: #0f1117; --surface: #1a1d27; --border: #2a2d3a;
    --text: #e2e8f0; --muted: #94a3b8; --accent: #6366f1;
    --green: #22c55e; --yellow: #eab308; --orange: #f97316; --red: #ef4444;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: var(--bg); color: var(--text); font-family: 'Inter', system-ui, sans-serif; padding: 2rem; }}
  h1 {{ font-size: 1.8rem; font-weight: 700; color: white; margin-bottom: 0.25rem; }}
  .subtitle {{ color: var(--muted); font-size: 0.9rem; margin-bottom: 2rem; }}
  .card {{ background: var(--surface); border: 1px solid var(--border); border-radius: 12px; padding: 1.5rem; margin-bottom: 1.5rem; }}
  .stats-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 1rem; }}
  .stat-card {{ background: var(--bg); border: 1px solid var(--border); border-radius: 8px; padding: 1rem; text-align: center; }}
  .stat-value {{ font-size: 2rem; font-weight: 700; }}
  .stat-label {{ font-size: 0.75rem; color: var(--muted); text-transform: uppercase; letter-spacing: 0.05em; margin-top: 0.25rem; }}
  table {{ width: 100%; border-collapse: collapse; }}
  th {{ text-align: left; padding: 0.75rem 1rem; color: var(--muted); font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; border-bottom: 1px solid var(--border); }}
  td {{ padding: 0.75rem 1rem; border-bottom: 1px solid var(--border); font-size: 0.9rem; }}
  tr:last-child td {{ border-bottom: none; }}
  .score-bar-bg {{ background: var(--border); border-radius: 4px; height: 8px; width: 120px; }}
  .score-bar-fill {{ height: 8px; border-radius: 4px; }}
  .score-green {{ color: var(--green); }}
  .score-yellow {{ color: var(--yellow); }}
  .score-orange {{ color: var(--orange); }}
  .score-red {{ color: var(--red); }}
  .fill-green {{ background: var(--green); }}
  .fill-yellow {{ background: var(--yellow); }}
  .fill-orange {{ background: var(--orange); }}
  .fill-red {{ background: var(--red); }}
  .badge {{ display: inline-block; padding: 0.2rem 0.6rem; border-radius: 4px; font-size: 0.8rem; font-weight: 600; }}
  .badge-pass {{ background: rgba(34,197,94,0.15); color: var(--green); }}
  .badge-fail {{ background: rgba(239,68,68,0.15); color: var(--red); }}
  details {{ margin-bottom: 0.5rem; }}
  summary {{ cursor: pointer; padding: 0.5rem; border-radius: 6px; }}
  summary:hover {{ background: var(--border); }}
  .sample-detail {{ padding: 0.75rem 0.5rem 0.75rem 1.5rem; font-size: 0.85rem; color: var(--muted); }}
  .reasoning {{ background: var(--bg); border-left: 3px solid var(--accent); padding: 0.5rem 1rem; border-radius: 0 6px 6px 0; margin-top: 0.5rem; font-size: 0.82rem; line-height: 1.5; }}
  h2 {{ font-size: 1.1rem; font-weight: 600; margin-bottom: 1rem; }}
  .ragcheck-footer {{ text-align: center; color: var(--muted); font-size: 0.8rem; margin-top: 3rem; }}
</style>
</head>
<body>

<h1>🔍 RAGcheck Evaluation Report</h1>
<div class="subtitle">Dataset: <strong>{dataset_name}</strong> &nbsp;·&nbsp; Judge: <strong>{judge_model}</strong> &nbsp;·&nbsp; Generated by ragcheck</div>

<div class="card">
  <div class="stats-grid">
    <div class="stat-card">
      <div class="stat-value {overall_color}">{overall_score}</div>
      <div class="stat-label">Overall Score</div>
    </div>
    <div class="stat-card">
      <div class="stat-value">{sample_count}</div>
      <div class="stat-label">Samples</div>
    </div>
    <div class="stat-card">
      <div class="stat-value">{metric_count}</div>
      <div class="stat-label">Metrics</div>
    </div>
    <div class="stat-card">
      <div class="stat-value">{pass_badge}</div>
      <div class="stat-label">Threshold</div>
    </div>
  </div>
</div>

<div class="card">
  <h2>Per-Metric Summary</h2>
  <table>
    <thead>
      <tr>
        <th>Metric</th><th>Mean</th><th>Min</th><th>Max</th><th>Std</th><th>Score</th><th>Errors</th>
      </tr>
    </thead>
    <tbody>
      {metric_rows}
    </tbody>
  </table>
</div>

<div class="card">
  <h2>Per-Sample Breakdown</h2>
  {sample_details}
</div>

<div class="ragcheck-footer">
  Generated by <a href="https://github.com/RajmaniShukla/ragcheck" style="color: var(--accent);">ragcheck</a>
</div>

</body>
</html>
"""


def _score_class(score: float) -> str:
    if score >= 0.8:
        return "green"
    elif score >= 0.6:
        return "yellow"
    elif score >= 0.4:
        return "orange"
    else:
        return "red"


def _metric_row(stat) -> str:
    cls = _score_class(stat.mean)
    fill_pct = round(stat.mean * 100)
    return f"""
      <tr>
        <td><strong>{stat.metric.value}</strong></td>
        <td class="score-{cls}"><strong>{stat.mean:.3f}</strong></td>
        <td>{stat.min:.3f}</td>
        <td>{stat.max:.3f}</td>
        <td>{stat.std:.3f}</td>
        <td>
          <div class="score-bar-bg">
            <div class="score-bar-fill fill-{cls}" style="width:{fill_pct}%"></div>
          </div>
        </td>
        <td>{"<span style='color:var(--red)'>" + str(stat.failed_samples) + "</span>" if stat.failed_samples else "<span style='color:var(--muted)'>0</span>"}</td>
      </tr>"""


def _sample_detail(i: int, result) -> str:
    q = result.sample.question[:120] + ("…" if len(result.sample.question) > 120 else "")
    agg = result.aggregate
    cls = _score_class(agg)
    score_rows = ""
    for ms in result.scores:
        sc = _score_class(ms.score)
        reasoning = f'<div class="reasoning">{ms.reasoning}</div>' if ms.reasoning else ""
        error = f'<div style="color:var(--red);font-size:0.8rem">Error: {ms.error}</div>' if ms.error else ""
        score_rows += f"""
        <div style="margin-bottom:0.5rem">
          <span style="color:var(--muted);font-size:0.8rem;min-width:200px;display:inline-block">{ms.metric.value}</span>
          <span class="score-{sc}"><strong>{ms.score:.3f}</strong></span>
          {reasoning}{error}
        </div>"""

    return f"""
  <details>
    <summary>
      <span style="color:var(--muted);font-size:0.8rem">#{i + 1}</span>
      &nbsp; {q}
      &nbsp; <span class="score-{cls}">({agg:.3f})</span>
    </summary>
    <div class="sample-detail">
      {score_rows}
    </div>
  </details>"""


def generate_html(report: EvalReport) -> str:
    """Render EvalReport as a self-contained HTML string."""
    dataset_name = report.dataset_name or "Unnamed Dataset"
    overall_cls = _score_class(report.overall_score)

    if report.passed is True:
        pass_badge = '<span class="badge badge-pass">✅ PASSED</span>'
    elif report.passed is False:
        pass_badge = '<span class="badge badge-fail">❌ FAILED</span>'
    else:
        pass_badge = '<span style="color:var(--muted)">—</span>'

    metric_rows = "".join(_metric_row(s) for s in report.aggregate_stats)
    sample_details = "".join(_sample_detail(i, r) for i, r in enumerate(report.results))

    return _TEMPLATE.format(
        dataset_name=dataset_name,
        judge_model=report.config.judge.model,
        overall_score=f"{report.overall_score:.3f}",
        overall_color=f"score-{overall_cls}",
        sample_count=len(report.results),
        metric_count=len(report.aggregate_stats),
        pass_badge=pass_badge,
        metric_rows=metric_rows,
        sample_details=sample_details,
    )


def save_html(report: EvalReport, path: str | Path) -> Path:
    """Generate and save the HTML report to a file."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    html = generate_html(report)
    p.write_text(html, encoding="utf-8")
    return p
