"""
Noise Sensitivity Evaluator
-----------------------------
Measures: How much does answer quality degrade when irrelevant chunks are injected?

Strategy:
  1. Score faithfulness on the original contexts (baseline).
  2. Inject one synthetic noise chunk (off-topic paragraph generated by the judge).
  3. Re-score faithfulness on the noisy context.
  4. score = 1 - |baseline - noisy| (high score = robust to noise)

Note: This evaluator makes 3 judge calls per sample (generate noise + 2 faithfulness scores).
"""
from __future__ import annotations

from ragcheck.core.evaluators.base import BaseEvaluator
from ragcheck.core.schema import EvalSample, MetricName, MetricScore

NOISE_GEN_PROMPT = """\
Generate a single short paragraph (2–3 sentences) that is completely unrelated to the following question.
The paragraph should look like plausible document text but contain NO information relevant to answering the question.
Return only the paragraph text, nothing else.

Question: {question}
"""

FAITHFULNESS_PROMPT = """\
You are evaluating RAG faithfulness.

Context:
{contexts}

Answer: {answer}

Rate how faithful the answer is to the context on a scale of 0–1.
Return JSON: {{"score": <float>, "reasoning": "<str>"}}
"""


class NoiseSensitivityEvaluator(BaseEvaluator):
    metric = MetricName.NOISE_SENSITIVITY

    async def evaluate(self, sample: EvalSample) -> MetricScore:
        try:
            # Step 1: Baseline faithfulness
            baseline_result = await self.judge.judge(
                FAITHFULNESS_PROMPT.format(
                    contexts=self._fmt_contexts(sample.contexts),
                    answer=sample.answer,
                )
            )
            baseline_score = baseline_result["score"]

            # Step 2: Generate a noise chunk
            noise_resp = await self.judge.judge(
                # Wrap noise gen prompt to return {"score": 0.5, "text": "..."}
                # We abuse the judge interface slightly here
                f'{NOISE_GEN_PROMPT.format(question=sample.question)}\n\n'
                'Return JSON: {"score": 0.5, "text": "<the paragraph>"}'
            )
            noise_chunk = noise_resp.get("text", "This is unrelated background information.")

            # Step 3: Noisy faithfulness
            noisy_contexts = sample.contexts + [noise_chunk]
            noisy_result = await self.judge.judge(
                FAITHFULNESS_PROMPT.format(
                    contexts=self._fmt_contexts(noisy_contexts),
                    answer=sample.answer,
                )
            )
            noisy_score = noisy_result["score"]

            # Step 4: Robustness = 1 - degradation
            degradation = abs(baseline_score - noisy_score)
            robustness = round(1.0 - degradation, 4)

            return MetricScore(
                metric=self.metric,
                score=robustness,
                reasoning=(
                    f"Baseline faithfulness: {baseline_score:.3f}. "
                    f"Noisy faithfulness: {noisy_score:.3f}. "
                    f"Degradation: {degradation:.3f}."
                ),
                details={
                    "baseline_faithfulness": baseline_score,
                    "noisy_faithfulness": noisy_score,
                    "degradation": degradation,
                    "injected_noise_chunk": noise_chunk,
                },
            )
        except Exception as exc:
            return self._error_score(str(exc))
